### ISSUE TITLE
Kernel Version Check Bonkinates

### ISSUE THREAD

**Issue by donaldsharp** [FRRouting/topotests#4]
This change:

diff --git a/lib/topotest.py b/lib/topotest.py
index 221910b..1fa4c83 100644
--- a/lib/topotest.py
+++ b/lib/topotest.py
@@ -158,6 +158,9 @@ class Router(Node):
                 print("LDP Test, but no ldpd compiled or installed")
                 return "LDP Test, but no ldpd compiled or installed"
             kernel_version = re.search(r'([0-9]+\.[0-9]+).*', platform.release())
+
+            print("Running Kernel Version: %s" % kernel_version)
+            print("Platform Release: %s" % platform.release())
             if kernel_version:
                 if float(kernel_version.group(1)) < 4.5:
                     print("LDP Test need Linux Kernel 4.5 minimum")

Gives us this output:

Running Kernel Version: <_sre.SRE_Match object at 0x7f25707e97b0>
Platform Release: 4.11.0-041100rc8-generic
LDP Test need Linux Kernel 4.5 minimum
SKIPPED

**Comment by rwestphal** [comment]
Fixed by #5
