### ISSUE TITLE
topotest.py version_cmp does wrong compare

### ISSUE THREAD

**Issue by mwinter-osr** [FRRouting/topotests#43]
version_cmp('3.0.2', '3.0.0') == 1
    version_cmp('3.0.2', '3.0') == 1

but

    version_cmp('3.0.2', '3') == -1

3.0.2 > 3, should return 1

**Comment by rzalamena** [comment]
Progress can be found at PR #45 .

**Comment by mwinter-osr** [comment]
Fixed by PR #45
