### ISSUE TITLE
support for testing vrf netns support for L3VPN testing

### ISSUE THREAD

**Issue by pguibert6WIND** [FRRouting/topotests#62]
change proposed in 
https://github.com/pguibert6WIND/topotests/tree/bgp_vrf_to_bgp_vpn-vmerge1-namingvrf
does the following:
- at least provide the vrf renaming per machine
- then provide a mechanism to test with vrf with netns.

**Comment by rzalamena** [comment]
The issue seems to be resolved and I'll close it.

Feel free to re-open it or open a new issue.
