### ISSUE TITLE
ISIS occasionally not converging 

### ISSUE THREAD

**Issue by louberger** [FRRouting/topotests#67]
e.g., see https://ci1.netdef.org/download/FRR-TOPOPR-T3B/build_logs/FRR-TOPOPR-T3B-150.log
failed to converge after 90 seconds!

build	13-Feb-2018 07:56:13	isis-topo1/test_isis_topo1.py::test_isis_convergence 2018-02-13 07:56:13,875 INFO: loading topology: test_isis_topo1
build	13-Feb-2018 07:56:13	2018-02-13 07:56:13,876 INFO: starting topology: test_isis_topo1
build	13-Feb-2018 07:56:13	2018-02-13 07:56:13,994 INFO: r4: waiting for zebra to start (1 seconds)
build	13-Feb-2018 07:56:15	2018-02-13 07:56:15,240 INFO: r5: waiting for zebra to start (1 seconds)
build	13-Feb-2018 07:56:16	2018-02-13 07:56:16,462 INFO: r1: waiting for zebra to start (1 seconds)
build	13-Feb-2018 07:56:17	2018-02-13 07:56:17,686 INFO: r2: waiting for zebra to start (1 seconds)
build	13-Feb-2018 07:56:18	2018-02-13 07:56:18,926 INFO: r3: waiting for zebra to start (1 seconds)
build	13-Feb-2018 07:56:20	2018-02-13 07:56:20,928 INFO: waiting for ISIS protocol to converge
error	13-Feb-2018 07:57:52	2018-02-13 07:57:52,393 ERROR: assert failed at "test_isis_topo1/test_isis_convergence": Router 'r4' topology mismatch after +91.27 secs

**Comment by louberger** [comment]
https://ci1.netdef.org/browse/FRR-TOPOPR-151 shows a successful run of the same code

**Comment by rzalamena** [comment]
Is this still happening?

**Comment by rzalamena** [comment]
I haven't seen this problem in a while, so I'm going to close this issue.

Feel free to re-open or create a new issue it if you see it.
