### ISSUE TITLE
bgp daemon crashes 

### ISSUE THREAD

**Issue by beneslami** [FRRouting/topotests#84]
when I type " rt vpn both 52:100", there is an error occur:
vtysh: error reading from bgpd: Success (0)Warning: closing connection to bgpd because of an I/o error!

**Comment by rzalamena** [comment]
Hi @beneslami ,

Are you having problems running topotests or writing them? Or you would like to report a FRR bug?

If you want to do the later, I'd suggest to open an issue in the FRR repo instead of here.

Here is the FRR repo issue section: https://github.com/FRRouting/frr/issues

**Comment by beneslami** [comment]
Hello @rzalamena 
Actually I'm not 100% sure that it is FRR bug.
I have my own topology which is a mix of cisco and frr routers.
For now I have some theoretical assumptions and I'm checking them right now.

**Comment by beneslami** [comment]
I found the solution
I should run mpls ldp first.
without running ldp, rd and rt won't work and bgp will be collapsed and the daemon will be off ( I don't know why)

**Comment by rzalamena** [comment]
This issue doesn't seem to be related with topotests, so I'm closing it. Feel free to open a new one if you find new problems.
