### ISSUE TITLE
problem with route deletion

### ISSUE THREAD

**Issue by beneslami** [FRRouting/topotests#99]
Hi all. This is my config from one PE side:
router bgp 200 vrf test
 bgp router-id 3.3.3.3
 !
 address-family ipv4 unicast
  redistribute static
  label vpn export 567
  rd vpn export 100:110
  rt vpn both 100:1000
  export vpn
  import vpn
 exit-address-family
!
ip route 4.4.4.4/32 100.3.4.4/24   (*)
-------------------------------------
I can see vpvn4 in other PE and this is ok. The problem is when I delete the static route (*) , I can still see the vpnv4 in other PE which this is not true.
How can I make this correct?

Thank you

**Comment by rzalamena** [comment]
This issue is being addressed here: https://github.com/FRRouting/frr/issues/2622

I'll close this issue since it has nothing to do with topotests. If you feel this should be add to a topology test then please open a new issue.
